type UserStatus = 'FIRST' | 'GOOGLE_SET' | 'NOTION_API_SET' | 'NOTION_SET' | 'FINISHED';
type UserPlan = 'FREE' | 'PRO' | 'SPONSOR';
type UserNotionProps = {
    title?: string;
    date?: string;
    description?: string;
    delete?: string;
    location?: string;
    calendar?: string;
};
export type UserDto = {
    id: number;
    name: string;
    email: string;
    imageUrl: string;
    opizeId: number;
    googleEmail: string;
    notionDatabaseId: string;
    lastCalendarSync: string;
    lastSyncStatus: string;
    status: UserStatus;
    isConnected: boolean;
    userPlan: UserPlan;
    userTimeZone: string;
    notionProps?: UserNotionProps;
    isWork: boolean;
    isAdmin: boolean;
    createdAt: string;
    syncYear: number;
    isPlanUnlimited: boolean;
    lastPaymentTime: string;
    nextPaymentTime: string;
};
